name: Build Easy Worship Android APK (Tablet Optimized)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type (debug/release)'
        required: false
        default: 'debug'

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          python3 \
          python3-dev \
          python3-pip \
          python3-setuptools \
          python3-wheel \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          libgstreamer1.0 \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          default-jdk \
          cython3

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython==0.29.33

    - name: Cache buildozer global directory
      uses: actions/cache@v3
      with:
        path: ~/.buildozer
        key: buildozer-global-${{ hashFiles('buildozer.spec') }}

    - name: Cache buildozer directory
      uses: actions/cache@v3
      with:
        path: .buildozer
        key: buildozer-${{ hashFiles('buildozer.spec') }}

    - name: Build APK with Buildozer (Tablet Optimized)
      run: |
        buildozer android debug
        
    - name: List build outputs
      run: |
        ls -la bin/
        
    - name: Rename APK for tablet
      run: |
        cd bin
        for file in *.apk; do
          mv "$file" "EasyWorshipApp-Tablet-${file}"
        done
        ls -la

    - name: Upload APK artifacts
      uses: actions/upload-artifact@v3
      with:
        name: EasyWorshipApp-Android-Tablet-APK
        path: bin/*.apk
        retention-days: 30

    - name: Create Release (if tagged)
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: bin/*.apk
        title: Easy Worship App for Android Tablets
        body: |
          🛐 Easy Worship App for Android Tablets
          
          **Tablet Optimized Features:**
          - ✅ Multi-orientation support (portrait/landscape)
          - ✅ Large screen optimization
          - ✅ Touch-friendly interface
          - ✅ 11 Bible translations
          - ✅ Works on Android 5.0+ tablets
          
          **Installation:**
          1. Download the APK file
          2. Enable "Unknown Sources" in Android settings
          3. Tap APK to install
          4. Grant internet permission
          
          **Supported devices:** Android tablets and phones running Android 5.0+
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
